[package]
name = "sqb-rs"
version = "0.1.0"
description = "Smash Ultimate Sequence Bank file tool"
authors = ["BenHall-7 <benjaminjahall@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "sqb"
path = "src/sqb/lib.rs"

[[bin]]
name = "sqb_yaml"
path = "src/sqb_yaml/main.rs"

[dependencies]
byteorder = "1.3.2"
hash40 = "0.1.0"
serde = { version = "1.0.98", features = ["derive"] }
indexmap = "1.2.0"